/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.testshared1.testdb_26may;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

/**
 * AssetReintegrationDocument generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`asset_reintegration_document`")
public class AssetReintegrationDocument implements Serializable {

    private Integer idAssetReintegrationDocument;
    @Type(type = "DateTime")
    private LocalDateTime noteRepaymentDate;
    private Boolean printedNote;
    private Integer userDevelops;
    private String observation;
    private Integer userLocation;
    private Integer userMode;
    private Date userFecha;
    private List<ListAssetReintegrated> listAssetReintegrateds = new ArrayList<>();

    @Id
    @Column(name = "`id_asset_reintegration_document`", nullable = false, scale = 0, precision = 10)
    public Integer getIdAssetReintegrationDocument() {
        return this.idAssetReintegrationDocument;
    }

    public void setIdAssetReintegrationDocument(Integer idAssetReintegrationDocument) {
        this.idAssetReintegrationDocument = idAssetReintegrationDocument;
    }

    @Column(name = "`note_repayment_date`", nullable = false)
    public LocalDateTime getNoteRepaymentDate() {
        return this.noteRepaymentDate;
    }

    public void setNoteRepaymentDate(LocalDateTime noteRepaymentDate) {
        this.noteRepaymentDate = noteRepaymentDate;
    }

    @Column(name = "`printed_note`", nullable = false)
    public Boolean isPrintedNote() {
        return this.printedNote;
    }

    public void setPrintedNote(Boolean printedNote) {
        this.printedNote = printedNote;
    }

    @Column(name = "`user_develops`", nullable = false, scale = 0, precision = 10)
    public Integer getUserDevelops() {
        return this.userDevelops;
    }

    public void setUserDevelops(Integer userDevelops) {
        this.userDevelops = userDevelops;
    }

    @Column(name = "`observation`", nullable = true, length = 255)
    public String getObservation() {
        return this.observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    @Column(name = "`user_location`", nullable = false, scale = 0, precision = 10)
    public Integer getUserLocation() {
        return this.userLocation;
    }

    public void setUserLocation(Integer userLocation) {
        this.userLocation = userLocation;
    }

    @Column(name = "`user_mode`", nullable = false, scale = 0, precision = 10)
    public Integer getUserMode() {
        return this.userMode;
    }

    public void setUserMode(Integer userMode) {
        this.userMode = userMode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "`user_fecha`", nullable = false)
    public Date getUserFecha() {
        return this.userFecha;
    }

    public void setUserFecha(Date userFecha) {
        this.userFecha = userFecha;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "assetReintegrationDocument")
    public List<ListAssetReintegrated> getListAssetReintegrateds() {
        return this.listAssetReintegrateds;
    }

    public void setListAssetReintegrateds(List<ListAssetReintegrated> listAssetReintegrateds) {
        this.listAssetReintegrateds = listAssetReintegrateds;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AssetReintegrationDocument)) return false;
        final AssetReintegrationDocument assetReintegrationDocument = (AssetReintegrationDocument) o;
        return Objects.equals(getIdAssetReintegrationDocument(), assetReintegrationDocument.getIdAssetReintegrationDocument());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIdAssetReintegrationDocument());
    }
}

