/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.testshared1.testdb_26may;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Assessment generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`assessment`")
public class Assessment implements Serializable {

    private Integer idAssessment;
    private Integer fkWorkPosition;
    private Integer userEvaluation;
    private String observation;
    private Integer userLocation;
    private Integer userMode;
    private Date userFecha;
    private List<AssessmentField> assessmentFields = new ArrayList<>();

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id_assessment`", nullable = false, scale = 0, precision = 10)
    public Integer getIdAssessment() {
        return this.idAssessment;
    }

    public void setIdAssessment(Integer idAssessment) {
        this.idAssessment = idAssessment;
    }

    @Column(name = "`fk_work_position`", nullable = true, scale = 0, precision = 10)
    public Integer getFkWorkPosition() {
        return this.fkWorkPosition;
    }

    public void setFkWorkPosition(Integer fkWorkPosition) {
        this.fkWorkPosition = fkWorkPosition;
    }

    @Column(name = "`user_evaluation`", nullable = false, scale = 0, precision = 10)
    public Integer getUserEvaluation() {
        return this.userEvaluation;
    }

    public void setUserEvaluation(Integer userEvaluation) {
        this.userEvaluation = userEvaluation;
    }

    @Column(name = "`observation`", nullable = false, length = 150)
    public String getObservation() {
        return this.observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    @Column(name = "`user_location`", nullable = false, scale = 0, precision = 10)
    public Integer getUserLocation() {
        return this.userLocation;
    }

    public void setUserLocation(Integer userLocation) {
        this.userLocation = userLocation;
    }

    @Column(name = "`user_mode`", nullable = false, scale = 0, precision = 10)
    public Integer getUserMode() {
        return this.userMode;
    }

    public void setUserMode(Integer userMode) {
        this.userMode = userMode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "`user_fecha`", nullable = false)
    public Date getUserFecha() {
        return this.userFecha;
    }

    public void setUserFecha(Date userFecha) {
        this.userFecha = userFecha;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "assessment")
    public List<AssessmentField> getAssessmentFields() {
        return this.assessmentFields;
    }

    public void setAssessmentFields(List<AssessmentField> assessmentFields) {
        this.assessmentFields = assessmentFields;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Assessment)) return false;
        final Assessment assessment = (Assessment) o;
        return Objects.equals(getIdAssessment(), assessment.getIdAssessment());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIdAssessment());
    }
}

