/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.testshared1.testdb_26may;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JustifiedTravelExpenseFile generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`justified_travel_expense_file`")
public class JustifiedTravelExpenseFile implements Serializable {

    private Integer idJustifiedTravelExpenseFile;
    private String fileName;
    private String description_;
    private String mimeType;
    private String filePath;
    private Integer userLocation;
    private Integer userMode;
    private Date userFecha;
    private TravelExpense travelExpense;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id_justified_travel_expense_file`", nullable = false, scale = 0, precision = 10)
    public Integer getIdJustifiedTravelExpenseFile() {
        return this.idJustifiedTravelExpenseFile;
    }

    public void setIdJustifiedTravelExpenseFile(Integer idJustifiedTravelExpenseFile) {
        this.idJustifiedTravelExpenseFile = idJustifiedTravelExpenseFile;
    }

    @Column(name = "`file_name`", nullable = false, length = 150)
    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Column(name = "`description?`", nullable = false, length = 150)
    public String getDescription_() {
        return this.description_;
    }

    public void setDescription_(String description_) {
        this.description_ = description_;
    }

    @Column(name = "`mime_type`", nullable = false, length = 150)
    public String getMimeType() {
        return this.mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    @Column(name = "`file_path`", nullable = false, length = 255)
    public String getFilePath() {
        return this.filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    @Column(name = "`user_location`", nullable = false, scale = 0, precision = 10)
    public Integer getUserLocation() {
        return this.userLocation;
    }

    public void setUserLocation(Integer userLocation) {
        this.userLocation = userLocation;
    }

    @Column(name = "`user_mode`", nullable = false, scale = 0, precision = 10)
    public Integer getUserMode() {
        return this.userMode;
    }

    public void setUserMode(Integer userMode) {
        this.userMode = userMode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "`user_fecha`", nullable = false)
    public Date getUserFecha() {
        return this.userFecha;
    }

    public void setUserFecha(Date userFecha) {
        this.userFecha = userFecha;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`fk_travel_expense`", referencedColumnName = "`id_travel_expense`", insertable = true, updatable = true)
    public TravelExpense getTravelExpense() {
        return this.travelExpense;
    }

    public void setTravelExpense(TravelExpense travelExpense) {
        this.travelExpense = travelExpense;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof JustifiedTravelExpenseFile)) return false;
        final JustifiedTravelExpenseFile justifiedTravelExpenseFile = (JustifiedTravelExpenseFile) o;
        return Objects.equals(getIdJustifiedTravelExpenseFile(), justifiedTravelExpenseFile.getIdJustifiedTravelExpenseFile());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIdJustifiedTravelExpenseFile());
    }
}

