/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.testshared1.testdb_26may;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ScheduleFixedDay generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`schedule_fixed_day`", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"`fk_schedule_fixed`", "`week_day`"})})
public class ScheduleFixedDay implements Serializable {

    private Integer idScheduleFixedDay;
    private Boolean weekDay;
    private Date checkIn;
    private Date lunchStartTime;
    private Date lunchHourOrder;
    private Date outputTime;
    private Integer userMode;
    private Date userFecha;
    private ScheduleFixed scheduleFixed;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id_schedule_fixed_day`", nullable = false, scale = 0, precision = 10)
    public Integer getIdScheduleFixedDay() {
        return this.idScheduleFixedDay;
    }

    public void setIdScheduleFixedDay(Integer idScheduleFixedDay) {
        this.idScheduleFixedDay = idScheduleFixedDay;
    }

    @Column(name = "`week_day`", nullable = false)
    public Boolean isWeekDay() {
        return this.weekDay;
    }

    public void setWeekDay(Boolean weekDay) {
        this.weekDay = weekDay;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "`check_in`", nullable = false)
    public Date getCheckIn() {
        return this.checkIn;
    }

    public void setCheckIn(Date checkIn) {
        this.checkIn = checkIn;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "`lunch_start_time`", nullable = false)
    public Date getLunchStartTime() {
        return this.lunchStartTime;
    }

    public void setLunchStartTime(Date lunchStartTime) {
        this.lunchStartTime = lunchStartTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "`lunch_hour_order`", nullable = false)
    public Date getLunchHourOrder() {
        return this.lunchHourOrder;
    }

    public void setLunchHourOrder(Date lunchHourOrder) {
        this.lunchHourOrder = lunchHourOrder;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "`output_time`", nullable = false)
    public Date getOutputTime() {
        return this.outputTime;
    }

    public void setOutputTime(Date outputTime) {
        this.outputTime = outputTime;
    }

    @Column(name = "`user_mode`", nullable = false, scale = 0, precision = 10)
    public Integer getUserMode() {
        return this.userMode;
    }

    public void setUserMode(Integer userMode) {
        this.userMode = userMode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "`user_fecha`", nullable = false)
    public Date getUserFecha() {
        return this.userFecha;
    }

    public void setUserFecha(Date userFecha) {
        this.userFecha = userFecha;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`fk_schedule_fixed`", referencedColumnName = "`id_schedule_fixed`", insertable = true, updatable = true)
    public ScheduleFixed getScheduleFixed() {
        return this.scheduleFixed;
    }

    public void setScheduleFixed(ScheduleFixed scheduleFixed) {
        this.scheduleFixed = scheduleFixed;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ScheduleFixedDay)) return false;
        final ScheduleFixedDay scheduleFixedDay = (ScheduleFixedDay) o;
        return Objects.equals(getIdScheduleFixedDay(), scheduleFixedDay.getIdScheduleFixedDay());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIdScheduleFixedDay());
    }
}

