/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.testshared1.testdb_26may.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testshared1.testdb_26may.DetallePlanillaEgresos;
import com.testshared1.testdb_26may.DetallePlanillaEgresosId;

/**
 * ServiceImpl object for domain model class DetallePlanillaEgresos.
 *
 * @see DetallePlanillaEgresos
 */
@Service("TestDB_26may.DetallePlanillaEgresosService")
public class DetallePlanillaEgresosServiceImpl implements DetallePlanillaEgresosService {

    private static final Logger LOGGER = LoggerFactory.getLogger(DetallePlanillaEgresosServiceImpl.class);

    @Autowired
    @Qualifier("TestDB_26may.DetallePlanillaEgresosDao")
    private WMGenericDao<DetallePlanillaEgresos, DetallePlanillaEgresosId> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<DetallePlanillaEgresos, DetallePlanillaEgresosId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

	@Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
	@Override
	public DetallePlanillaEgresos getById(DetallePlanillaEgresosId detalleplanillaegresosId) throws EntityNotFoundException {
        LOGGER.debug("Finding DetallePlanillaEgresos by id: {}", detalleplanillaegresosId);
        DetallePlanillaEgresos detalleplanillaegresos = this.wmGenericDao.findById(detalleplanillaegresosId);
        if (detalleplanillaegresos == null){
            LOGGER.debug("No DetallePlanillaEgresos found with id: {}", detalleplanillaegresosId);
            throw new EntityNotFoundException(String.valueOf(detalleplanillaegresosId));
        }
        return detalleplanillaegresos;
    }

	@Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
	@Override
	public Page<DetallePlanillaEgresos> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all DetallePlanillaEgresos");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
    @Override
    public Page<DetallePlanillaEgresos> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all DetallePlanillaEgresos");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service TestDB_26may for table DetallePlanillaEgresos to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
    @SuppressWarnings("unchecked")
	@Override
    public Page<DetallePlanillaEgresos> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable) {
        LOGGER.debug("Fetching all associated");
        return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
    }
}

