/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.testshared1.testdb_26may.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testshared1.testdb_26may.ListAssetDiscarded;

/**
 * ServiceImpl object for domain model class ListAssetDiscarded.
 *
 * @see ListAssetDiscarded
 */
@Service("TestDB_26may.ListAssetDiscardedService")
public class ListAssetDiscardedServiceImpl implements ListAssetDiscardedService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ListAssetDiscardedServiceImpl.class);

    @Autowired
    @Qualifier("TestDB_26may.ListAssetDiscardedDao")
    private WMGenericDao<ListAssetDiscarded, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<ListAssetDiscarded, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "TestDB_26mayTransactionManager")
    @Override
	public ListAssetDiscarded create(ListAssetDiscarded listassetdiscarded) {
        LOGGER.debug("Creating a new ListAssetDiscarded with information: {}", listassetdiscarded);
        return this.wmGenericDao.create(listassetdiscarded);
    }

	@Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
	@Override
	public ListAssetDiscarded getById(Integer listassetdiscardedId) throws EntityNotFoundException {
        LOGGER.debug("Finding ListAssetDiscarded by id: {}", listassetdiscardedId);
        ListAssetDiscarded listassetdiscarded = this.wmGenericDao.findById(listassetdiscardedId);
        if (listassetdiscarded == null){
            LOGGER.debug("No ListAssetDiscarded found with id: {}", listassetdiscardedId);
            throw new EntityNotFoundException(String.valueOf(listassetdiscardedId));
        }
        return listassetdiscarded;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "TestDB_26mayTransactionManager")
	@Override
	public ListAssetDiscarded update(ListAssetDiscarded listassetdiscarded) throws EntityNotFoundException {
        LOGGER.debug("Updating ListAssetDiscarded with information: {}", listassetdiscarded);
        this.wmGenericDao.update(listassetdiscarded);

        Integer listassetdiscardedId = listassetdiscarded.getIdListAssetDiscarded();

        return this.wmGenericDao.findById(listassetdiscardedId);
    }

    @Transactional(value = "TestDB_26mayTransactionManager")
	@Override
	public ListAssetDiscarded delete(Integer listassetdiscardedId) throws EntityNotFoundException {
        LOGGER.debug("Deleting ListAssetDiscarded with id: {}", listassetdiscardedId);
        ListAssetDiscarded deleted = this.wmGenericDao.findById(listassetdiscardedId);
        if (deleted == null) {
            LOGGER.debug("No ListAssetDiscarded found with id: {}", listassetdiscardedId);
            throw new EntityNotFoundException(String.valueOf(listassetdiscardedId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
	@Override
	public Page<ListAssetDiscarded> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all ListAssetDiscardeds");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
    @Override
    public Page<ListAssetDiscarded> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all ListAssetDiscardeds");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service TestDB_26may for table ListAssetDiscarded to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
    @SuppressWarnings("unchecked")
	@Override
    public Page<ListAssetDiscarded> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable) {
        LOGGER.debug("Fetching all associated");
        return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
    }
}

