/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.testshared1.testdb_26may.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testshared1.testdb_26may.TypeAnnouncement;

/**
 * ServiceImpl object for domain model class TypeAnnouncement.
 *
 * @see TypeAnnouncement
 */
@Service("TestDB_26may.TypeAnnouncementService")
public class TypeAnnouncementServiceImpl implements TypeAnnouncementService {

    private static final Logger LOGGER = LoggerFactory.getLogger(TypeAnnouncementServiceImpl.class);

    @Autowired
    @Qualifier("TestDB_26may.TypeAnnouncementDao")
    private WMGenericDao<TypeAnnouncement, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<TypeAnnouncement, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "TestDB_26mayTransactionManager")
    @Override
	public TypeAnnouncement create(TypeAnnouncement typeannouncement) {
        LOGGER.debug("Creating a new TypeAnnouncement with information: {}", typeannouncement);
        return this.wmGenericDao.create(typeannouncement);
    }

	@Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
	@Override
	public TypeAnnouncement getById(Integer typeannouncementId) throws EntityNotFoundException {
        LOGGER.debug("Finding TypeAnnouncement by id: {}", typeannouncementId);
        TypeAnnouncement typeannouncement = this.wmGenericDao.findById(typeannouncementId);
        if (typeannouncement == null){
            LOGGER.debug("No TypeAnnouncement found with id: {}", typeannouncementId);
            throw new EntityNotFoundException(String.valueOf(typeannouncementId));
        }
        return typeannouncement;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "TestDB_26mayTransactionManager")
	@Override
	public TypeAnnouncement update(TypeAnnouncement typeannouncement) throws EntityNotFoundException {
        LOGGER.debug("Updating TypeAnnouncement with information: {}", typeannouncement);
        this.wmGenericDao.update(typeannouncement);

        Integer typeannouncementId = typeannouncement.getIdTypeAnnouncement();

        return this.wmGenericDao.findById(typeannouncementId);
    }

    @Transactional(value = "TestDB_26mayTransactionManager")
	@Override
	public TypeAnnouncement delete(Integer typeannouncementId) throws EntityNotFoundException {
        LOGGER.debug("Deleting TypeAnnouncement with id: {}", typeannouncementId);
        TypeAnnouncement deleted = this.wmGenericDao.findById(typeannouncementId);
        if (deleted == null) {
            LOGGER.debug("No TypeAnnouncement found with id: {}", typeannouncementId);
            throw new EntityNotFoundException(String.valueOf(typeannouncementId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
	@Override
	public Page<TypeAnnouncement> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all TypeAnnouncements");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
    @Override
    public Page<TypeAnnouncement> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all TypeAnnouncements");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service TestDB_26may for table TypeAnnouncement to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
    @SuppressWarnings("unchecked")
	@Override
    public Page<TypeAnnouncement> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable) {
        LOGGER.debug("Fetching all associated");
        return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
    }
}

