/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.testshared1.testdb_26may.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testshared1.testdb_26may.WorkPositionResponsibility;

/**
 * ServiceImpl object for domain model class WorkPositionResponsibility.
 *
 * @see WorkPositionResponsibility
 */
@Service("TestDB_26may.WorkPositionResponsibilityService")
public class WorkPositionResponsibilityServiceImpl implements WorkPositionResponsibilityService {

    private static final Logger LOGGER = LoggerFactory.getLogger(WorkPositionResponsibilityServiceImpl.class);

    @Autowired
    @Qualifier("TestDB_26may.WorkPositionResponsibilityDao")
    private WMGenericDao<WorkPositionResponsibility, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<WorkPositionResponsibility, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "TestDB_26mayTransactionManager")
    @Override
	public WorkPositionResponsibility create(WorkPositionResponsibility workpositionresponsibility) {
        LOGGER.debug("Creating a new WorkPositionResponsibility with information: {}", workpositionresponsibility);
        return this.wmGenericDao.create(workpositionresponsibility);
    }

	@Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
	@Override
	public WorkPositionResponsibility getById(Integer workpositionresponsibilityId) throws EntityNotFoundException {
        LOGGER.debug("Finding WorkPositionResponsibility by id: {}", workpositionresponsibilityId);
        WorkPositionResponsibility workpositionresponsibility = this.wmGenericDao.findById(workpositionresponsibilityId);
        if (workpositionresponsibility == null){
            LOGGER.debug("No WorkPositionResponsibility found with id: {}", workpositionresponsibilityId);
            throw new EntityNotFoundException(String.valueOf(workpositionresponsibilityId));
        }
        return workpositionresponsibility;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "TestDB_26mayTransactionManager")
	@Override
	public WorkPositionResponsibility update(WorkPositionResponsibility workpositionresponsibility) throws EntityNotFoundException {
        LOGGER.debug("Updating WorkPositionResponsibility with information: {}", workpositionresponsibility);
        this.wmGenericDao.update(workpositionresponsibility);

        Integer workpositionresponsibilityId = workpositionresponsibility.getIdWorkPositionResponsibility();

        return this.wmGenericDao.findById(workpositionresponsibilityId);
    }

    @Transactional(value = "TestDB_26mayTransactionManager")
	@Override
	public WorkPositionResponsibility delete(Integer workpositionresponsibilityId) throws EntityNotFoundException {
        LOGGER.debug("Deleting WorkPositionResponsibility with id: {}", workpositionresponsibilityId);
        WorkPositionResponsibility deleted = this.wmGenericDao.findById(workpositionresponsibilityId);
        if (deleted == null) {
            LOGGER.debug("No WorkPositionResponsibility found with id: {}", workpositionresponsibilityId);
            throw new EntityNotFoundException(String.valueOf(workpositionresponsibilityId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
	@Override
	public Page<WorkPositionResponsibility> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all WorkPositionResponsibilities");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
    @Override
    public Page<WorkPositionResponsibility> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all WorkPositionResponsibilities");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service TestDB_26may for table WorkPositionResponsibility to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "TestDB_26mayTransactionManager")
    @SuppressWarnings("unchecked")
	@Override
    public Page<WorkPositionResponsibility> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable) {
        LOGGER.debug("Fetching all associated");
        return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
    }
}

